# Generated by Django 4.2.7 on 2023-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='advert_video',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
