# Generated by Django 4.2.7 on 2023-12-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
