# Generated by Django 4.2.7 on 2023-12-23 13:49

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='images/')),
                ('paragraph1', models.TextField(max_length=150)),
                ('paragraph2', models.TextField(max_length=150)),
                ('paragraph3', models.TextField(max_length=150)),
                ('paragraph4', models.TextField(max_length=150)),
                ('paragraph5', models.TextField(max_length=150)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('published', blog.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'ordering': ['name'],
            },
        ),
    ]
