# Generated by Django 4.2.7 on 2023-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph1',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph2',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph3',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph4',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph5',
            field=models.TextField(max_length=700),
        ),
    ]
