# Generated by Django 4.2.7 on 2023-12-24 08:06

from django.db import migrations, models
import django.utils.timezone
import testimonials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='images/')),
                ('message', models.TextField(max_length=150)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('published', testimonials.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['name'],
            },
        ),
    ]
