# Generated by Django 4.2.7 on 2023-12-23 19:27

from django.db import migrations, models
import django.utils.timezone
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('img1', models.ImageField(upload_to='images/')),
                ('advert_video', models.FileField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('published', gallery.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
