# Generated by Django 4.2.7 on 2023-12-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
