# Generated by Django 4.2.7 on 2023-12-23 13:49

from django.db import migrations, models
import django.utils.timezone
import newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='images/')),
                ('paragraph1', models.TextField(max_length=150)),
                ('paragraph2', models.TextField(max_length=150)),
                ('paragraph3', models.TextField(max_length=150)),
                ('paragraph4', models.TextField(max_length=150)),
                ('paragraph5', models.TextField(max_length=150)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('published', newsletter.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['name'],
            },
        ),
    ]
